### ISSUE TITLE
add resources and references

### ISSUE THREAD

**Issue by tusharnankani** [pratik-choudhari/docker-guide#1]
Hi @pratik-choudhari 

It is super awesome that you are learning/building in public, and helping others learn too! 😄 

I have been wanting to know it as well, but when I started out with [this](https://github.com/pratik-choudhari/docker-guide/blob/main/markdown_files/what_is_docker.md), some concepts are not clear for me, I am not able to properly imagine and understand, and there could be 2 reasons for it precisely, I haven't explored much yet hence it might be difficult to understand the internal working, and my projects have not yet been scaled up yet, to use Docker, maybe that's why right now might not be a good time for me to start. Let me know if I am wrong?

Also, if you could add (video) references in the files if the user wants to understand more and explore/learn further.

**Comment by pratik-choudhari** [comment]
@tusharnankani Yes, you are right, a person should at least know about virtual machines and why isolation is required. Also, I will add the video references today. I will also also include a few projects that are using docker so that along with learning there can be hands-on examples.

**Comment by pratik-choudhari** [comment]
Hey, I have added video links as well as links to few articles. Thanks for opening this issue! I encourage you to share this repo so most could benefit from this.
